import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/login">Login</Link>
            </li>
            <li>
              <Link href="/vaccinationEssentials">Essentials</Link>
            </li>
            <li>
              <Link href="/vaccineDevelopment">Development</Link>
            </li>
            <li>
              <Link href="/specializedVaccination">Vaccination</Link>
            </li>
            <li>
              <Link href="/doctorResources">Resources</Link>
            </li>
            <li>
              <Link href="/about">About us</Link>
            </li>
            <li>
              <Link href="/privacyPolicy">Privacy Policy</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
